name: CI
# Workflow file for windows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  job:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore vcpkg and GTK environment
        uses: actions/cache@v2
        id: vcpkg-cache
        with:
          path: |
            ${{ env.VCPKG_ROOT }}
            ${{ github.workspace }}\build\vcpkg_installed
            ${{ env.VCPKG_ROOT }}\.git
            ${{ env.VCPKG_ROOT }}\buildtrees
            ${{ env.VCPKG_ROOT }}\packages
            ${{ env.VCPKG_ROOT }}\downloads
            ${{ github.workspace }}\target
          key: |
            ${{ hashFiles( 'Cargo.lock' ) }}-${{ runner.os }}-cache-key-v1

      - name: Install vcpkg for windows
        if: ${{ runner.os == 'Windows' && steps.vcpkg-cache.outputs.cache-hit != 'true' }}
        run: |
          cd ${{ github.workspace }}
          mkdir build -force
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          #.\bootstrap-vcpkg.bat
          #.\vcpkg install gtk --triplet x64-windows

      - name: Build GTK App for Windows
        shell: powershell
        run: |
          wget -Uri "https://udomain.dl.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip" -OutFile "pkg-config.zip" 
          Expand-Archive -Path .\pkg-config.zip -DestinationPath .
          pkg-config --version

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
        env:
          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
          VCPKGDIR: "${{ github.workspace }}/vcpkg"
          PKG_CONFIG_PATH: "%VCPKGDIR%\\installed\\x64-windows\\lib\\pkgconfig"
          GTK_LIB_DIR: "%VCPKGDIR%\\installed\\x64-windows\\lib"
      #   PATH: ${{ github.workspace }}\pkg-config-lite-0.28-1\bin;%VCPKGDIR%\installed\x64-windows\bin;%PATH%

      - name: Build Exe
#        env:
#          VCPKG_ROOT: "${{ github.workspace }}/vcpkg"
#          PKG_CONFIG_PATH: "${{ github.workspace }}/vcpkg\\installed\\x64-windows\\lib\\pkgconfig"
#          GTK_LIB_DIR: "${{ github.workspace }}/vcpkg\\installed\\x64-windows\\lib"
        shell: bash
        run: |
           pwd
           cd \d\a\app-gtk-rs\app-gtk-rs
           ls 
           cd ./vcpkg/installed/x64-windows/lib
           ls
          
#          cd ${{ github.workspace }}/vcpkg && ls
#          echo "*************************************************************************"
#         cd ${{ github.workspace }}/vcpkg/installed/x64-windows/lib && ls
#          echo "*************************************************************************"
#          cd ${{ github.workspace }}/vcpkg/installed/x64-windows/lib/pkgconfig && ls
#          set VCPKG_ROOT="${{ github.workspace }}/vcpkg"
#          set PKG_CONFIG_PATH="${{ github.workspace }}/vcpkg/installed/x64-windows/lib/pkgconfig"
#          set GTK_LIB_DIR="${{ github.workspace }}/vcpkg/installed/x64-windows/lib"
#          set PATH=${{ github.workspace }}/pkg-config-lite-0.28-1/bin;${{ github.workspace }}/vcpkg/installed/x64-windows/bin;%VCPKG_ROOT%;%GTK_LIB_DIR%;%PKG_CONFIG_PATH%;%PATH%
#          pkg-config --version

#          set VCPKG_ROOT
#          set PKG_CONFIG_PATH
#          set GTK_LIB_DIR
#          set PATH

#          cargo build --release
#          7z
